### ISSUE TITLE
Syntax error on token "default", Identifier expected

### ISSUE THREAD

**Issue by taehwoi** [ePages-de/restdocs-openapi#190]
```java
parameterWithName("example").default(3)
        .type(SimpleType.INTEGER)
        // ....
```

java 14, restdocs-api-spec 0.13.0

It seems like the .default method collides with java's default keyword.
Is it possible to provide a similar method with a different name (e.g. defaultValue) ?

**Comment by taehioum** [comment]
Thx! have a nice day
