### ISSUE TITLE
[Info] Similar project

### ISSUE THREAD

**Issue by linuxomaniac** [ePages-de/restdocs-openapi#33]
Hey!
I think we started the exact same project in the same time, so in my view it would be interesting for both of us to look at each other's code: [restdocs-openapi](lhttps://github.com/linuxomaniac/restdocs-openapi)
I only had a little to do before with Java, Kotlin Maven etc, so I think what I did is a little lame and is a bit of an amateur project (like the commit messages…).
But if you want to grab ideas from it (like the Maven plugin), you're of course free to go!

**Comment by linuxomaniac** [comment]
Ah, sorry, I was convinced that I put the link, but I totally forgot…

Here it is: https://github.com/linuxomaniac/restdocs-openapi

**Comment by mduesterhoeft** [comment]
Looks like you started from restdocs-raml - like we did?! What do you think - is our version more advanced that yours? If so - why not join our effort and contribute here?

**Comment by mduesterhoeft** [comment]
Great - thanks!
