### ISSUE TITLE
conflict with https://github.com/ajoberstar/reckon gradle plugin

### ISSUE THREAD

**Issue by thugcee** [ePages-de/restdocs-openapi#35]
I've added _restdocs-openapi_ plugin to my `build.gradle` and now building fails with:

```
> Failed to apply plugin [id 'com.epages.restdocs-openapi']
   > Could not create an instance of type com.epages.restdocs.openapi.gradle.RestdocsOpenApiPluginExtension_Decorated.
      > org.ajoberstar.reckon.gradle.ReckonPlugin$DelayedVersion cannot be cast to java.lang.String
```

**Comment by mduesterhoeft** [comment]
Do you have a sample project so I could reproduce the case to have a deeper look?

**Comment by thugcee** [comment]
here it is: https://github.com/thugcee/gradle-recon-restdocs-openapi-test

**Comment by mduesterhoeft** [comment]
Can you try release 0.2.3 - there we are more careful when accessing the project version property.

**Comment by thugcee** [comment]
Yes, it works now. Thank you!
