### ISSUE TITLE
[Enhancement] Read the Javadoc to document beans

### ISSUE THREAD

**Issue by linuxomaniac** [ePages-de/restdocs-openapi#38]
I found this project that aims to automatically generate documentation for a Spring project: https://github.com/ScaCap/spring-auto-restdocs
Unfortunately, the output format is only to be used with AsciiDoctor and this library is not so flexible.

Would it then be possible to add a javadoc processor to restdocs-openapi to obtain and generate the beans documentation?

**Comment by mduesterhoeft** [comment]
I think this is best done with https://github.com/springfox/springfox
